FROM mu-777/grpc-cpp

RUN DEBIAN_FRONTEND="noninteractive" apt-get update && apt-get -y install tzdata

RUN apt-get update \
  && apt-get install -y \
      sudo build-essential gcc g++ gdb clang tar libpython3-dev python3-pip \
      bash-completion astyle git vim iputils-ping net-tools dnsutils wget \
  && rm -rf /var/lib/apt/lists/*

RUN echo ALL ALL=\(ALL:ALL\) NOPASSWD: ALL>> /etc/sudoers

COPY ./entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]