# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: threadctrl.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10threadctrl.proto\x12\nthreadctrl\"\x1b\n\x0cRunThreadReq\x12\x0b\n\x03key\x18\x01 \x01(\t\"\"\n\rRunThreadResp\x12\x11\n\tisSuccess\x18\x01 \x01(\x08\"\x12\n\x10StopAllThreadReq\"&\n\x11StopAllThreadResp\x12\x11\n\tisSuccess\x18\x01 \x01(\x08\x32\xa3\x01\n\rThreadControl\x12\x42\n\tRunThread\x12\x18.threadctrl.RunThreadReq\x1a\x19.threadctrl.RunThreadResp\"\x00\x12N\n\rStopAllThread\x12\x1c.threadctrl.StopAllThreadReq\x1a\x1d.threadctrl.StopAllThreadResp\"\x00\x62\x06proto3')



_RUNTHREADREQ = DESCRIPTOR.message_types_by_name['RunThreadReq']
_RUNTHREADRESP = DESCRIPTOR.message_types_by_name['RunThreadResp']
_STOPALLTHREADREQ = DESCRIPTOR.message_types_by_name['StopAllThreadReq']
_STOPALLTHREADRESP = DESCRIPTOR.message_types_by_name['StopAllThreadResp']
RunThreadReq = _reflection.GeneratedProtocolMessageType('RunThreadReq', (_message.Message,), {
  'DESCRIPTOR' : _RUNTHREADREQ,
  '__module__' : 'threadctrl_pb2'
  # @@protoc_insertion_point(class_scope:threadctrl.RunThreadReq)
  })
_sym_db.RegisterMessage(RunThreadReq)

RunThreadResp = _reflection.GeneratedProtocolMessageType('RunThreadResp', (_message.Message,), {
  'DESCRIPTOR' : _RUNTHREADRESP,
  '__module__' : 'threadctrl_pb2'
  # @@protoc_insertion_point(class_scope:threadctrl.RunThreadResp)
  })
_sym_db.RegisterMessage(RunThreadResp)

StopAllThreadReq = _reflection.GeneratedProtocolMessageType('StopAllThreadReq', (_message.Message,), {
  'DESCRIPTOR' : _STOPALLTHREADREQ,
  '__module__' : 'threadctrl_pb2'
  # @@protoc_insertion_point(class_scope:threadctrl.StopAllThreadReq)
  })
_sym_db.RegisterMessage(StopAllThreadReq)

StopAllThreadResp = _reflection.GeneratedProtocolMessageType('StopAllThreadResp', (_message.Message,), {
  'DESCRIPTOR' : _STOPALLTHREADRESP,
  '__module__' : 'threadctrl_pb2'
  # @@protoc_insertion_point(class_scope:threadctrl.StopAllThreadResp)
  })
_sym_db.RegisterMessage(StopAllThreadResp)

_THREADCONTROL = DESCRIPTOR.services_by_name['ThreadControl']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RUNTHREADREQ._serialized_start=32
  _RUNTHREADREQ._serialized_end=59
  _RUNTHREADRESP._serialized_start=61
  _RUNTHREADRESP._serialized_end=95
  _STOPALLTHREADREQ._serialized_start=97
  _STOPALLTHREADREQ._serialized_end=115
  _STOPALLTHREADRESP._serialized_start=117
  _STOPALLTHREADRESP._serialized_end=155
  _THREADCONTROL._serialized_start=158
  _THREADCONTROL._serialized_end=321
# @@protoc_insertion_point(module_scope)
